# This file is used to create a deployment and a service for the mongo database

# Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  # This is the number of replicas that we want to create
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      # This is the container that we want to run
      # Give the image and the other configurations here
      containers:
        - name: webapp
          image: mongo-express:latest
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                # Tells to get the value from mongo-secrets.yaml file
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_USER
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_PASSWORD
            - name: ME_CONFIG_MONGODB_SERVER
              valueFrom:
                # Tells to get the value from mongo-config.yaml file
                configMapKeyRef:
                  name: mongo-config
                  key: MONGO_URL

# Breaking down the yaml file
---
# Service

apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  selector:
    # This label is same as the Deployment.
    app: webapp
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
